# Generated by Django 5.1.3 on 2025-11-12 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                (
                    "processador",
                    models.CharField(max_length=100, verbose_name="Processador"),
                ),
                (
                    "memoria_ram",
                    models.CharField(max_length=50, verbose_name="Memória RAM"),
                ),
                (
                    "armazenamento",
                    models.CharField(max_length=50, verbose_name="Armazenamento"),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="notebooks/"),
                ),
                (
                    "informacoes_extras",
                    models.TextField(
                        blank=True, null=True, verbose_name="Informações extras"
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_entrega",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de entrega para o responsável",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("emprestado", "Emprestado"),
                            ("manutencao", "Em manutenção"),
                            ("reciclado", "Reciclado"),
                            ("pendente", "Pendente"),
                            ("recebido", "Recebido"),
                        ],
                        default="pendente",
                        help_text="Atualize o status conforme o ciclo de uso do notebook.",
                        max_length=20,
                    ),
                ),
                (
                    "validado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o notebook foi validado pelo administrador.",
                    ),
                ),
                (
                    "em_uso",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o notebook está atualmente em uso.",
                    ),
                ),
                (
                    "data_reciclagem",
                    models.DateField(
                        blank=True,
                        help_text="Data em que o notebook foi marcado como reciclado.",
                        null=True,
                        verbose_name="Data da Reciclagem",
                    ),
                ),
                (
                    "destino_reciclagem",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes sobre para onde o notebook foi reciclado ou como seus componentes foram reaproveitados.",
                        null=True,
                        verbose_name="Destino/Reaproveitamento da Reciclagem",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Doador/Cadastrador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_manutencao",
                    models.CharField(
                        choices=[
                            ("reparo", "Reparo"),
                            ("limpeza", "Limpeza"),
                            ("atualizacao", "Atualização de Software/Hardware"),
                            ("diagnostico", "Diagnóstico"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Manutenção",
                    ),
                ),
                (
                    "data_manutencao",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da Manutenção",
                    ),
                ),
                (
                    "descricao_problema",
                    models.TextField(
                        blank=True,
                        help_text="Descreva o problema encontrado (se houver).",
                        null=True,
                        verbose_name="Descrição do Problema",
                    ),
                ),
                (
                    "solucao_aplicada",
                    models.TextField(
                        blank=True,
                        help_text="Descreva a solução ou serviço realizado.",
                        null=True,
                        verbose_name="Solução Aplicada",
                    ),
                ),
                (
                    "custo_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Custo estimado da manutenção, se aplicável.",
                        max_digits=8,
                        null=True,
                        verbose_name="Custo Estimado (R$)",
                    ),
                ),
                (
                    "pronto_para_uso",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o notebook está pronto para ser disponibilizado novamente.",
                        verbose_name="Pronto para Uso",
                    ),
                ),
                (
                    "administrador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Administrador que registrou a manutenção.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        help_text="Notebook que recebeu a manutenção.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manutencoes",
                        to="EconoteApp.notebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutenção",
                "verbose_name_plural": "Manutenções",
                "ordering": ["-data_manutencao"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[("aluno", "Aluno"), ("professor", "Professor")],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.CharField(max_length=20, unique=True)),
                ("curso", models.CharField(max_length=100)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EconoteApp.perfilusuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siape", models.CharField(max_length=20, unique=True)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EconoteApp.perfilusuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitacaoNotebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("semestre", models.CharField(max_length=20)),
                ("historico", models.FileField(upload_to="historicos/")),
                (
                    "contexto",
                    models.CharField(
                        choices=[
                            ("Baixo", "Baixo"),
                            ("Médio", "Médio"),
                            ("Alto", "Alto"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tempo_uso",
                    models.CharField(
                        choices=[
                            ("1_mês", "1 mês"),
                            ("2_meses", "2 meses"),
                            ("3_meses", "3 meses"),
                            ("mais_3_meses", "Mais de 3 meses"),
                        ],
                        max_length=20,
                    ),
                ),
                ("justificativa", models.TextField()),
                (
                    "indicacao_professor",
                    models.TextField(
                        blank=True, null=True, verbose_name="Indicação do Professor"
                    ),
                ),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovado", "Aprovado"),
                            ("Recusado", "Recusado"),
                            ("Lista de Espera", "Lista de Espera"),
                            ("devolucao_pendente", "Devolução Pendente"),
                            ("Devolvido", "Devolvido"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "tempo_concedido",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_mês", "1 mês"),
                            ("2_meses", "2 meses"),
                            ("3_meses", "3 meses"),
                            ("mais_3_meses", "Mais de 3 meses"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("data_avaliacao", models.DateTimeField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "avaliado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avaliacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indicado_por_professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicacoes_feitas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Indicado Por",
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="EconoteApp.notebook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmprestimoNotebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_retirada",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Data em que o notebook foi retirado.",
                    ),
                ),
                (
                    "data_prevista_devolucao",
                    models.DateField(
                        blank=True,
                        help_text="Data prevista para a devolução do notebook.",
                        null=True,
                    ),
                ),
                (
                    "data_devolucao_real",
                    models.DateField(
                        blank=True,
                        help_text="Data real da devolução do notebook.",
                        null=True,
                    ),
                ),
                (
                    "status_emprestimo",
                    models.CharField(
                        choices=[
                            ("emprestado", "Emprestado"),
                            ("devolvido", "Devolvido"),
                            ("atrasado", "Atrasado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="emprestado",
                        help_text="Status atual do empréstimo.",
                        max_length=20,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        help_text="Aluno que recebeu o empréstimo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "avaliado_por_admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Administrador que registrou/gerenciou o empréstimo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emprestimos_administrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        help_text="Notebook emprestado.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EconoteApp.notebook",
                    ),
                ),
                (
                    "solicitacao",
                    models.OneToOneField(
                        help_text="Solicitação que originou este empréstimo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprestimo",
                        to="EconoteApp.solicitacaonotebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empréstimo de Notebook",
                "verbose_name_plural": "Empréstimos de Notebooks",
            },
        ),
        migrations.CreateModel(
            name="DevolucaoNotebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("nao_preciso", "Não preciso mais do notebook"),
                            ("defeito", "Notebook com defeito"),
                            ("uso_concluido", "Uso concluído antes do prazo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_sugerida", models.DateField()),
                ("detalhes", models.TextField(blank=True, null=True)),
                ("compromisso_aceito", models.BooleanField(default=False)),
                ("data_envio", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovada", "Aprovada"),
                            ("recusada", "Recusada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devolucao",
                        to="EconoteApp.solicitacaonotebook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvaliacaoAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_avaliacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Data em que a avaliação foi registrada.",
                    ),
                ),
                (
                    "desempenho_academico_obs",
                    models.TextField(
                        blank=True,
                        help_text="Descreva o impacto do notebook no desempenho acadêmico do aluno.",
                        null=True,
                        verbose_name="Observações sobre Desempenho Acadêmico",
                    ),
                ),
                (
                    "conduta_obs",
                    models.TextField(
                        blank=True,
                        help_text="Descreva a conduta do aluno durante o período de empréstimo (cuidado, comunicação, etc.).",
                        null=True,
                        verbose_name="Observações sobre Conduta",
                    ),
                ),
                (
                    "recomendacao_futura",
                    models.CharField(
                        choices=[
                            ("sim", "Sim"),
                            ("nao", "Não"),
                            ("condicional", "Condicional"),
                        ],
                        default="sim",
                        help_text="Recomendaria o aluno para futuros empréstimos?",
                        max_length=20,
                        verbose_name="Recomendação para Futuros Empréstimos",
                    ),
                ),
                (
                    "observacoes_gerais",
                    models.TextField(
                        blank=True,
                        help_text="Outras observações relevantes sobre o aluno.",
                        null=True,
                        verbose_name="Observações Gerais",
                    ),
                ),
                (
                    "foto_recebimento",
                    models.ImageField(
                        blank=True,
                        help_text="Foto do estado do notebook no momento da devolução.",
                        null=True,
                        upload_to="avaliacoes_notebooks/",
                        verbose_name="Foto do Notebook no Recebimento",
                    ),
                ),
                (
                    "administrador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Administrador que registrou a avaliação.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avaliacoes_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        help_text="Aluno que está sendo avaliado.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_recebidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emprestimo",
                    models.OneToOneField(
                        help_text="Empréstimo ao qual esta avaliação se refere.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao_aluno",
                        to="EconoteApp.emprestimonotebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Aluno",
                "verbose_name_plural": "Avaliações de Alunos",
                "unique_together": {("emprestimo",)},
            },
        ),
    ]
