# Generated by Django 5.1.3 on 2025-11-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="verification_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
