# Generated by Django 5.1.3 on 2025-05-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devolucao",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="devolucao",
            name="notebook",
        ),
        migrations.RemoveField(
            model_name="emprestimo",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="emprestimo",
            name="notebook",
        ),
        migrations.RemoveField(
            model_name="listaespera",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="listaespera",
            name="notebook",
        ),
        migrations.RemoveField(
            model_name="manutencao",
            name="notebook",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="cadastrado_por",
        ),
        migrations.RemoveField(
            model_name="reciclagem",
            name="notebook",
        ),
        migrations.RenameField(
            model_name="professor",
            old_name="matricula",
            new_name="SIAPE",
        ),
        migrations.DeleteModel(
            name="AvaliacaoAluno",
        ),
        migrations.DeleteModel(
            name="Devolucao",
        ),
        migrations.DeleteModel(
            name="Emprestimo",
        ),
        migrations.DeleteModel(
            name="ListaEspera",
        ),
        migrations.DeleteModel(
            name="Manutencao",
        ),
        migrations.DeleteModel(
            name="Notebook",
        ),
        migrations.DeleteModel(
            name="Reciclagem",
        ),
    ]
