# Generated by Django 5.1.3 on 2025-06-01 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EconoteApp",
            "0002_remove_devolucao_aluno_remove_devolucao_notebook_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("processador", models.CharField(max_length=100)),
                ("memoria_ram", models.CharField(max_length=50)),
                ("armazenamento", models.CharField(max_length=50)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="notebooks/"),
                ),
                ("informacoes_extras", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
