# Generated by Django 5.1.3 on 2025-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0003_notebook"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="data_entrega",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de entrega para o responsável"
            ),
        ),
    ]
