# Generated by Django 5.1.3 on 2025-06-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0004_notebook_data_entrega"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="status",
            field=models.CharField(
                choices=[("pendente", "Pendente"), ("recebido", "Validado")],
                default="pendente",
                max_length=10,
            ),
        ),
    ]
