# Generated by Django 5.1.3 on 2025-06-05 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0005_notebook_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="professor",
            old_name="SIAPE",
            new_name="siape",
        ),
        migrations.AddField(
            model_name="notebook",
            name="validado",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o notebook foi validado pelo administrador.",
            ),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="armazenamento",
            field=models.CharField(max_length=50, verbose_name="Armazenamento"),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="informacoes_extras",
            field=models.TextField(
                blank=True, null=True, verbose_name="Informações extras"
            ),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="memoria_ram",
            field=models.CharField(max_length=50, verbose_name="Memória RAM"),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="processador",
            field=models.CharField(max_length=100, verbose_name="Processador"),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("recebido", "Recebido"),
                    ("oky", "Disponível"),
                ],
                default="pendente",
                help_text="Marque como 'oky' para disponibilizar o notebook para solicitação.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="SolicitacaoNotebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("semestre", models.CharField(max_length=20)),
                ("historico", models.FileField(upload_to="historicos/")),
                (
                    "contexto",
                    models.CharField(
                        choices=[
                            ("Baixo", "Baixo"),
                            ("Médio", "Médio"),
                            ("Alto", "Alto"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "recomendacao",
                    models.CharField(
                        choices=[("Sim", "Sim"), ("Não", "Não")], max_length=5
                    ),
                ),
                (
                    "tempo_uso",
                    models.CharField(
                        choices=[
                            ("1_mês", "1 mês"),
                            ("2_meses", "2 meses"),
                            ("3_meses", "3 meses"),
                            ("mais_3_meses", "Mais de 3 meses"),
                        ],
                        max_length=20,
                    ),
                ),
                ("justificativa", models.TextField()),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Pendente", max_length=20)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
