# Generated by Django 5.1.3 on 2025-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0006_rename_siape_professor_siape_notebook_validado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaonotebook",
            name="tempo_concedido",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1_mês", "1 mês"),
                    ("2_meses", "2 meses"),
                    ("3_meses", "3 meses"),
                    ("mais_3_meses", "Mais de 3 meses"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
