# Generated by Django 5.1.3 on 2025-06-05 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0007_solicitacaonotebook_tempo_concedido"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="em_uso",
            field=models.BooleanField(
                default=False, help_text="Indica se o notebook está atualmente em uso."
            ),
        ),
        migrations.AddField(
            model_name="solicitacaonotebook",
            name="avaliado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaonotebook",
            name="data_avaliacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaonotebook",
            name="notebook",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="EconoteApp.notebook",
            ),
        ),
    ]
