# Generated by Django 5.1.3 on 2025-06-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EconoteApp",
            "0008_notebook_em_uso_solicitacaonotebook_avaliado_por_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaonotebook",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Recusado", "Recusado"),
                    ("Lista de Espera", "Lista de Espera"),
                ],
                default="Pendente",
                max_length=20,
            ),
        ),
    ]
