# Generated by Django 5.1.3 on 2025-06-06 03:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0009_alter_solicitacaonotebook_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DevolucaoNotebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("nao_preciso", "Não preciso mais do notebook"),
                            ("defeito", "Notebook com defeito"),
                            ("uso_concluido", "Uso concluído antes do prazo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_sugerida", models.DateField()),
                ("detalhes", models.TextField(blank=True, null=True)),
                ("compromisso_aceito", models.BooleanField(default=False)),
                ("data_envio", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovada", "Aprovada"),
                            ("recusada", "Recusada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EconoteApp.solicitacaonotebook",
                    ),
                ),
            ],
        ),
    ]
