# Generated by Django 5.1.3 on 2025-06-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0010_devolucaonotebook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebook",
            name="status",
            field=models.CharField(
                choices=[
                    ("disponivel", "Disponível"),
                    ("emprestado", "Emprestado"),
                    ("manutencao", "Em manutenção"),
                    ("reciclado", "Reciclado"),
                    ("pendente", "Pendente"),
                    ("recebido", "Recebido"),
                ],
                default="pendente",
                help_text="Atualize o status conforme o ciclo de uso do notebook.",
                max_length=20,
            ),
        ),
    ]
