# Generated by Django 5.1.3 on 2025-06-12 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0011_alter_notebook_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmprestimoNotebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_retirada",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Data em que o notebook foi retirado.",
                    ),
                ),
                (
                    "data_prevista_devolucao",
                    models.DateField(
                        blank=True,
                        help_text="Data prevista para a devolução do notebook.",
                        null=True,
                    ),
                ),
                (
                    "data_devolucao_real",
                    models.DateField(
                        blank=True,
                        help_text="Data real da devolução do notebook.",
                        null=True,
                    ),
                ),
                (
                    "status_emprestimo",
                    models.CharField(
                        choices=[
                            ("emprestado", "Emprestado"),
                            ("devolvido", "Devolvido"),
                            ("atrasado", "Atrasado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="emprestado",
                        help_text="Status atual do empréstimo.",
                        max_length=20,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        help_text="Aluno que recebeu o empréstimo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "avaliado_por_admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Administrador que registrou/gerenciou o empréstimo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emprestimos_administrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        help_text="Notebook emprestado.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EconoteApp.notebook",
                    ),
                ),
                (
                    "solicitacao",
                    models.OneToOneField(
                        help_text="Solicitação que originou este empréstimo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprestimo",
                        to="EconoteApp.solicitacaonotebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empréstimo de Notebook",
                "verbose_name_plural": "Empréstimos de Notebooks",
            },
        ),
    ]
