# Generated by Django 5.1.3 on 2025-06-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0012_emprestimonotebook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaonotebook",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Recusado", "Recusado"),
                    ("Lista de Espera", "Lista de Espera"),
                    ("Devolvido", "Devolvido"),
                ],
                default="Pendente",
                max_length=20,
            ),
        ),
    ]
