# Generated by Django 5.1.3 on 2025-06-13 19:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0013_alter_solicitacaonotebook_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="data_cadastro",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data de Cadastro",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="devolucaonotebook",
            name="solicitacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devolucao",
                to="EconoteApp.solicitacaonotebook",
            ),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Doador/Cadastrador",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaonotebook",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Recusado", "Recusado"),
                    ("Lista de Espera", "Lista de Espera"),
                    ("devolucao_pendente", "Devolução Pendente"),
                    ("Devolvido", "Devolvido"),
                ],
                default="Pendente",
                max_length=20,
            ),
        ),
    ]
