# Generated by Django 5.1.3 on 2025-06-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0014_notebook_data_cadastro_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="ira",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="status",
        ),
        migrations.RemoveField(
            model_name="solicitacaonotebook",
            name="recomendacao",
        ),
    ]
