# Generated by Django 5.1.3 on 2025-06-16 21:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EconoteApp", "0016_solicitacaonotebook_indicacao_professor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvaliacaoAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_avaliacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Data em que a avaliação foi registrada.",
                    ),
                ),
                (
                    "desempenho_academico_obs",
                    models.TextField(
                        blank=True,
                        help_text="Descreva o impacto do notebook no desempenho acadêmico do aluno.",
                        null=True,
                        verbose_name="Observações sobre Desempenho Acadêmico",
                    ),
                ),
                (
                    "conduta_obs",
                    models.TextField(
                        blank=True,
                        help_text="Descreva a conduta do aluno durante o período de empréstimo (cuidado, comunicação, etc.).",
                        null=True,
                        verbose_name="Observações sobre Conduta",
                    ),
                ),
                (
                    "recomendacao_futura",
                    models.CharField(
                        choices=[
                            ("sim", "Sim"),
                            ("nao", "Não"),
                            ("condicional", "Condicional"),
                        ],
                        default="sim",
                        help_text="Recomendaria o aluno para futuros empréstimos?",
                        max_length=20,
                        verbose_name="Recomendação para Futuros Empréstimos",
                    ),
                ),
                (
                    "observacoes_gerais",
                    models.TextField(
                        blank=True,
                        help_text="Outras observações relevantes sobre o aluno.",
                        null=True,
                        verbose_name="Observações Gerais",
                    ),
                ),
                (
                    "administrador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Administrador que registrou a avaliação.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avaliacoes_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        help_text="Aluno que está sendo avaliado.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_recebidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emprestimo",
                    models.OneToOneField(
                        help_text="Empréstimo ao qual esta avaliação se refere.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao_aluno",
                        to="EconoteApp.emprestimonotebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Aluno",
                "verbose_name_plural": "Avaliações de Alunos",
                "unique_together": {("emprestimo",)},
            },
        ),
    ]
