# Generated by Django 5.1.3 on 2025-07-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EconoteApp",
            "0018_notebook_data_reciclagem_notebook_destino_reciclagem_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaoaluno",
            name="foto_recebimento",
            field=models.ImageField(
                blank=True,
                help_text="Foto do estado do notebook no momento da devolução.",
                null=True,
                upload_to="avaliacoes_notebooks/",
                verbose_name="Foto do Notebook no Recebimento",
            ),
        ),
    ]
